# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcd6465f15f0fd98842bae8499df836005fb63e4b76f4ef0843ea22e48cdd9bd11b77fda5a6340251ed81d09e5b38c03a64113795757368750df2bb51b3d2ca0

test:
  secret_key_base: 6dce92ac36226ecf9b53bd018e312b77df0d006e262a5f9ca11cdf7075be8b21b975a1590ceb3922e02a0e7fc1f5a0903c7f89f4c2e2b7690bf9246ae2c66cf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
